export const ACTION_TYPES = {
  GET_ROOMS_SUCCESS: "GET_ROOMS_SUCCESS",
  GET_ROOMS_FAIL: "GET_ROOMS_FAIL",

  GET_ROOM_DETAIL_SUCCESS: "GET_ROOM_DETAIL_SUCCESS",
  GET_ROOM_DETAIL_FAIL: "GET_ROOM_DETAIL_FAIL",

  REGISTER_USER_REQUEST: "REGISTER_USER_REQUEST",
  REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
  REGISTER_USER_FAIL: "REGISTER_USER_FAIL",

  LOAD_USER_REQUEST: "LOAD_USER_REQUEST",
  LOAD_USER_SUCCESS: "LOAD_USER_SUCCESS",
  LOAD_USER_FAIL: "LOAD_USER_FAIL",

  UPDATE_USER_PROFILE_REQUEST: "UPDATE_USER_PROFILE_REQUEST",
  UPDATE_USER_PROFILE_SUCCESS: "UPDATE_USER_PROFILE_SUCCESS",
  UPDATE_USER_PROFILE_FAIL: "UPDATE_USER_PROFILE_FAIL",

  CHECK_BOOKING_REQUEST: "CHECK_BOOKING_REQUEST",
  CHECK_BOOKING_SUCCESS: "CHECK_BOOKING_SUCCESS",
  CHECK_BOOKING_FAIL: "CHECK_BOOKING_FAIL",

  BOOKED_DATES_SUCCESS: "BOOKED_DATES_SUCCESS",
  BOOKED_DATES_FAIL: "BOOKED_DATES_FAIL",

  MY_BOOKINGS_SUCCESS: "MY_BOOKINGS_SUCCESS",
  MY_BOOKINGS_FAIL: "MY_BOOKINGS_FAIL",

  BOOKING_DETAILS_SUCCESS: "BOOKING_DETAILS_SUCCESS",
  BOOKING_DETAILS_FAIL: "BOOKING_DETAILS_FAIL",

  CLEAR_ERROR: "CLEAR_ERROR"
};
