export const ACTION_TYPES = {
  GET_ROOMS_SUCCESS: "GET_ROOMS_SUCCESS",
  GET_ROOMS_FAIL: "GET_ROOMS_FAIL",

  GET_ROOM_DETAIL_SUCCESS: "GET_ROOM_DETAIL_SUCCESS",
  GET_ROOM_DETAIL_FAIL: "GET_ROOM_DETAIL_FAIL",

  REGISTER_USER_REQUEST: "REGISTER_USER_REQUEST",
  REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
  REGISTER_USER_FAIL: "REGISTER_USER_FAIL",

  LOAD_USER_REQUEST: "LOAD_USER_REQUEST",
  LOAD_USER_SUCCESS: "LOAD_USER_SUCCESS",
  LOAD_USER_FAIL: "LOAD_USER_FAIL",

  CLEAR_ERROR: "CLEAR_ERROR"
};
