export const ACTION_TYPES = {
  GET_ROOMS_SUCCESS: "GET_ROOMS_SUCCESS",
  GET_ROOMS_FAIL: "GET_ROOMS_FAIL",

  GET_ROOM_DETAIL_SUCCESS: "GET_ROOM_DETAIL_SUCCESS",
  GET_ROOM_DETAIL_FAIL: "GET_ROOM_DETAIL_FAIL",

  CLEAR_ERROR: "CLEAR_ERROR"
};
